### PR TITLE
Conform to PEP8

### PR DESCRIPTION
**Pull request by super3**
Also rename vars shadowing built-ins.

### CODE REVIEW

**Comment by yimingliu** [comment]
Thanks!  I haven't had a chance to test it, but I've been meaning to PEP8-fy this module and just never had the time.

Could I get you to do two minor things?

- In the new `NatPMP` class, the `proto` variable is hard-coded inline to 1 and 2.  Could use the `NATPMP_PROTOCOL_TCP` and `NATPMP_PROTOCOL_UDP` constants already in the module to make it more readable.

- I wish something `netifaces` existed back when I wrote this first, and would definitely have used it, since gateway detection was the most fragile part of the code.  However, now I have legacy code deployed based on NATPMP.py, that doesn't rely on installing a third-party dependency.  Can you do an ImportError exception check in `get_gateway_addr` to see netifaces can be imported, and fallback to the netstat-based hack otherwise?

**Comment by super3** [comment]
No problem. Part of our own PEP8 cleanup, so I figured best to contribute
back.

I'll tackle them tomorrow morning. Tested locally and on Travis-CI. Should
be zero functional changes.

**Comment by super3** [comment]
@yimingliu Believe I implemented what was requested.

**Comment by super3** [comment]
Note credit goes to @robertsdotpm for the get_gateway_addr() with netifaces. I just did the PEP8 stuff.

**Pull request merged**
